name: Python package

on: [push, pull_request]

env:
  PIP_ROOT_USER_ACTION: ignore

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest --upgrade
          pip install ruff --upgrade
          pip install mypy --upgrade
          pip install -e ".[dev]"

      - uses: pre-commit/action@v3.0.1

      - name: Lint with ruff
        run: |
          ruff format .
          ruff check .

      - name: Static type checking
        run: |
          mypy "src"

      - name: Run tests
        run: pytest tests

# pyproject-tools

# Put your content here

# pyproject-tools
